### ISSUE TITLE
micoreBingen不能正确运行

### ISSUE THREAD

**Issue by haswelliris** [XiuYuLi/miCore#1]
两个主要问题：
1. gfxcoder.cpp中的`gfxcoder::metadata_set_arg`没有声明，同时该方法的`metadata->args[argidx++]={size,offs,kind,type};`变量`argidx`未被定义  
2. micoreBingen运行时报错，istrlen函数访问了空指针。具体调用栈：
```
istrlen (src=<optimized out>) at ./include/strop.h:20
msgpack_encode_str (str=0x0, dst=0x0) at ./include/hsaco/msgpack.h:12
generator::metadata_get_args_size  at ./source/hsaco/generator.cpp:54
generator::get_section_size_note at ./source/hsaco/generator.cpp:110
·········
```
调试发现问题点应该是`generator.cpp`54行的`o+=msgpack_encode_str( nullptr, k_kind[meta->args[i].kind] );`  
其中`meta->args[i].kind`的值为16，`k_kind`是长度为2的数组，越界了。打印其他args[i].kind .type查看，很多时候都超出了k_kind k_type的范围。  
感觉是metadata初始化时的问题，希望您能看一下，感谢

**Comment by XiuYuLi** [comment]
你好，其实MICORE最开始是基于COV2 ABI开发测试的，后来迁移到COV3 ABI，也可以正常使用（在ROCm3.3下的metadata中的.args段不是必须的），再后来.metadata中的args信息变成了必须的，我只改变了hsaco generator,但相应的kernel并未更改，所以你可以把generator.c中关于args相关的代码注释掉或者手动给所有kernel添加上args信息，谢谢！

**Comment by XiuYuLi** [comment]
使用x64 release mode,其它mode未配置，如有其它问题随时留言

**Comment by haswelliris** [comment]
miCore还遇到以下问题：
1. include/conv.c的`lk_perm_flip( &ctx->kern_perm[0], p, x, b, s );`，context_t没有定义kern_perm
2. 还是conv.h和conv.c的问题：`build_param_ufconv`有定义实现，`build_param_ufbconv`和`build_param_uffconv`只有声明无实现，这块逻辑我还没弄清楚，暂时不知道怎么改。
3. `param_ufconv_t`结构体没有定义amag和cmag，加上`magic_t amag; magic_t cmag ; `后解决
4. 函数`lk_uffconv`声明了没实现，看上去是拼错了?能找到lk_ufconv的定义，但是没有lk_uf**f**conv。改一下解决  

另外注释掉micore_fconv和micore_bconv相关代码是可以通过编译的了。  
上面提到的1、2点还需要您帮忙看看。

**Comment by XiuYuLi** [comment]
抱歉，是我太不严谨了，更新文件时操作失误，会尽快更正～
